import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import type { AgentConfig, AgentOptions, AgentResult } from "./agent-adapter.js";

const executeAgentMock = vi.hoisted(() =>
  vi.fn<(prompt: string, config: AgentConfig, options?: AgentOptions) => AgentResult>()
);
const detectAgentMock = vi.hoisted(() => vi.fn<() => "claude" | "codex" | null>());
const isAgentAvailableMock = vi.hoisted(() => vi.fn<(provider: "claude" | "codex") => boolean>());

vi.mock("./agent-adapter.js", async () => {
  const actual = await vi.importActual<typeof import("./agent-adapter.js")>("./agent-adapter.js");
  return {
    ...actual,
    executeAgent: executeAgentMock,
    detectAgent: detectAgentMock,
    isAgentAvailable: isAgentAvailableMock,
  };
});

import { cmdAdd, cmdDone, cmdInit, cmdRun } from "./techlead-commands.js";

function readTaskJson(cwd: string): Record<string, unknown> {
  const tasksDir = path.join(cwd, ".techlead", "tasks");
  const taskDirs = fs.readdirSync(tasksDir);
  const taskPath = path.join(tasksDir, taskDirs[0], "task.json");
  return JSON.parse(fs.readFileSync(taskPath, "utf8")) as Record<string, unknown>;
}

function getTaskDir(cwd: string): string {
  const tasksDir = path.join(cwd, ".techlead", "tasks");
  const taskDirs = fs.readdirSync(tasksDir);
  return path.join(tasksDir, taskDirs[0]);
}

describe("techlead commands smoke", () => {
  const originalCwd = process.cwd();
  const MOCK_COMPLETED_AT = "2024-03-03T13:00:00.000Z";
  let tempDir = "";

  beforeEach(() => {
    tempDir = fs.mkdtempSync(path.join(os.tmpdir(), "techlead-commands-smoke-"));
    process.chdir(tempDir);
    executeAgentMock.mockReset();
    detectAgentMock.mockReset();
    isAgentAvailableMock.mockReset();
    detectAgentMock.mockReturnValue("claude");
    isAgentAvailableMock.mockImplementation(() => true);
  });

  afterEach(() => {
    process.chdir(originalCwd);
    fs.rmSync(tempDir, { recursive: true, force: true });
  });

  it("completes one task end-to-end and creates phase artifacts", () => {
    cmdInit();
    cmdAdd("smoke task");

    executeAgentMock
      .mockReturnValueOnce({
        success: true,
        content: "Plan generated",
      })
      .mockReturnValueOnce({
        success: true,
        content: 'Step done\n\n<!-- STATUS: {"completed": true} -->',
      })
      .mockReturnValueOnce({
        success: true,
        content: 'Review passed\n\n<!-- VERDICT: {"result": "PASS", "critical_count": 0} -->',
      })
      .mockReturnValueOnce({
        success: true,
        content: 'Test passed\n\n<!-- VERDICT: {"result": "PASS", "critical_count": 0} -->',
      });

    cmdRun();
    cmdRun();
    cmdRun();

    const task = readTaskJson(tempDir);
    const taskDir = getTaskDir(tempDir);

    expect(task.status).toBe("done");
    expect(task.phase).toBe("completed");
    expect(fs.existsSync(path.join(taskDir, "plan", "discussion.md"))).toBe(true);
    expect(fs.existsSync(path.join(taskDir, "plan", "plan.md"))).toBe(true);
    expect(fs.existsSync(path.join(taskDir, "work-log.md"))).toBe(true);
    expect(fs.existsSync(path.join(taskDir, "review", "reviewer-1.md"))).toBe(true);
    expect(fs.existsSync(path.join(taskDir, "test", "adversarial-test.md"))).toBe(true);
    expect(executeAgentMock).toHaveBeenCalledTimes(4);
  });

  it("uses configured provider and falls back to secondary provider on failure", () => {
    cmdInit();
    cmdAdd("fallback task");

    fs.writeFileSync(
      path.join(tempDir, ".techlead", "config.yaml"),
      [
        "agent:",
        "  provider: claude",
        "  model: opus",
        "  timeout_ms: 120000",
        "  max_budget_usd: 3",
      ].join("\n"),
      "utf8"
    );

    executeAgentMock
      .mockImplementationOnce(() => ({
        success: false,
        content: "",
        error: "primary provider failed",
      }))
      .mockImplementationOnce(() => ({
        success: true,
        content: "Plan generated by fallback",
      }));

    cmdRun();

    const task = readTaskJson(tempDir);

    expect(detectAgentMock).not.toHaveBeenCalled();
    expect(executeAgentMock).toHaveBeenCalledTimes(2);
    expect(executeAgentMock.mock.calls[0]?.[1].provider).toBe("claude");
    expect(executeAgentMock.mock.calls[0]?.[1].model).toBe("opus");
    expect(executeAgentMock.mock.calls[1]?.[1].provider).toBe("codex");
    expect(executeAgentMock.mock.calls[1]?.[1].model).toBe("gpt-4o");
    expect(task.status).toBe("in_progress");
    expect(task.phase).toBe("plan");
  });

  it("repairs invalid done state before execution and prevents false completion", () => {
    cmdInit();
    cmdAdd("repair invalid done");

    const taskDir = getTaskDir(tempDir);
    const taskPath = path.join(taskDir, "task.json");
    const task = JSON.parse(fs.readFileSync(taskPath, "utf8")) as Record<string, unknown>;
    task.status = "done";
    task.phase = "exec";
    task.review_passed = false;
    task.test_passed = false;
    task.completed_at = MOCK_COMPLETED_AT;
    fs.writeFileSync(taskPath, `${JSON.stringify(task, null, 2)}\n`, "utf8");

    executeAgentMock.mockReturnValueOnce({
      success: true,
      content: 'Working\n\n<!-- STATUS: {"completed": false} -->',
    });

    cmdRun();

    const repaired = readTaskJson(tempDir);
    expect(repaired.status).toBe("in_progress");
    expect(repaired.phase).toBe("exec");
    expect(repaired.completed_at).toBeNull();
    expect(executeAgentMock).toHaveBeenCalledTimes(1);
  });

  it("rejects task state mutation written by agent during exec", () => {
    cmdInit();
    cmdAdd("mutation guard");

    executeAgentMock
      .mockReturnValueOnce({
        success: true,
        content: "Plan generated",
      })
      .mockImplementationOnce(() => {
        const taskDir = getTaskDir(tempDir);
        const taskPath = path.join(taskDir, "task.json");
        const raw = JSON.parse(fs.readFileSync(taskPath, "utf8")) as Record<string, unknown>;
        raw.status = "done";
        raw.phase = "exec";
        raw.completed_at = MOCK_COMPLETED_AT;
        raw.review_passed = true;
        raw.test_passed = true;
        raw.review_attempts = 999;
        raw.test_attempts = 999;
        fs.writeFileSync(taskPath, `${JSON.stringify(raw, null, 2)}\n`, "utf8");
        return {
          success: true,
          content: 'Still running\n\n<!-- STATUS: {"completed": false} -->',
        };
      });

    cmdRun();
    cmdRun();
    cmdRun();

    const guarded = readTaskJson(tempDir);
    expect(guarded.status).toBe("in_progress");
    expect(guarded.phase).toBe("exec");
    expect(guarded.completed_at).toBeNull();
    expect(guarded.review_passed).not.toBe(true);
    expect(guarded.test_passed).not.toBe(true);
    expect(guarded.review_attempts ?? 0).toBe(0);
    expect(guarded.test_attempts ?? 0).toBe(0);
  });

  it("blocks cmdDone when review gate has not passed", () => {
    cmdInit();
    cmdAdd("done guard");

    const taskDir = getTaskDir(tempDir);
    const taskPath = path.join(taskDir, "task.json");
    const task = JSON.parse(fs.readFileSync(taskPath, "utf8")) as Record<string, unknown>;
    task.status = "testing";
    task.phase = "test";
    task.test_passed = true;
    task.review_passed = false;
    fs.writeFileSync(taskPath, `${JSON.stringify(task, null, 2)}\n`, "utf8");

    cmdDone("T-001");

    const after = readTaskJson(tempDir);
    expect(after.status).toBe("testing");
    expect(after.phase).toBe("test");
  });
});
