#!/usr/bin/env node

import { writeFileSync, readFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));

function getGitCommitId() {
  try {
    return execSync("git rev-parse --short HEAD", { encoding: "utf-8" }).trim();
  } catch (error) {
    console.warn(`Warning: Could not get git commit hash: ${error.message}`);
    return "unknown";
  }
}

function generateVersion() {
  const pkg = JSON.parse(readFileSync(join(__dirname, "../package.json"), "utf-8"));

  const versionInfo = {
    version: pkg.version,
    commit: getGitCommitId(),
  };

  // Generate a TypeScript file instead of JSON so tsc compiles it into dist/
  const tsContent = `// This file is auto-generated by scripts/generate-version.mjs
// Do not edit manually

export const version = "${versionInfo.version}";
export const commit = "${versionInfo.commit}";
`;

  const outputPath = join(__dirname, "../src/version.ts");
  writeFileSync(outputPath, tsContent);
  console.log(`Generated version: ${versionInfo.version} (${versionInfo.commit})`);
}

generateVersion();
